### ISSUE TITLE
Missing line in GeometricObjectsDemo

### ISSUE THREAD

**Issue by dmgroppe** [lorensen/VTKExamples#237]
You need to add the following line:
using System.Runtime.InteropServices;

to this example:
https://lorensen.github.io/VTKExamples/site/CSharp/GeometricObjects/GeometricObjectsDemo/

because the example uses the Marshal class.

**Comment by lorensen** [comment]
David, thanks for the sharp changes. We could use help in updating them.
Neither Andrew nor I are familiar with csharp.

**Comment by lorensen** [comment]
Create a merge request and we'll review and merge.

**Comment by dmgroppe** [comment]
Great. Will do.
Thanks Bill.
   -David

**Comment by lorensen** [comment]
Fixed here: https://lastpass.com/index.php?&ac=1&lpnorefresh=1&fromwebsite=1&newvault=1&nk=1
