### ISSUE TITLE
Minor bug in ImageReader2Factory example

### ISSUE THREAD

**Issue by dmgroppe** [lorensen/VTKExamples#238]
The line:
actor.SetInput(reader.GetOutput());

in:
https://lorensen.github.io/VTKExamples/site/CSharp/IO/ImageReader2Factory/

should be:
actor.SetInputData(reader.GetOutput());

**Comment by lorensen** [comment]
Fixed with https://github.com/lorensen/VTKExamples/commit/fe218e71858652f781c85a143f9c87d4047a8abc
