### ISSUE TITLE
Webpage fix 

### ISSUE THREAD

**Issue by chakravarthi589** [lorensen/VTKExamples#316]
@lorensen 

Please fix this as marked in the attached snapshot (https://lorensen.github.io/VTKExamples/site/Java/PolyData/ColorDisconnectedRegions/)
![image](https://user-images.githubusercontent.com/16251538/50424051-cb97f080-08a1-11e9-8093-93cf8cd1df0a.png)

**Comment by chakravarthi589** [comment]
Please check this also. - https://lorensen.github.io/VTKExamples/site/Java/PolyData/Outline/
![image](https://user-images.githubusercontent.com/16251538/50424085-23365c00-08a2-11e9-8fda-618962ab7abb.png)

**Comment by chakravarthi589** [comment]
@lorensen 
I have found similar issues in the webpage.  (https://lorensen.github.io/VTKExamples/site/)
but i dont know whether it is worth bringing to your notice as it may seem as small/negligible thing.
Also, in few c++ examples,  programs will have few headers declared but never used. is that fine?

**Comment by lorensen** [comment]
This is a feature I just added. If an example exits in another language,
the web page builder adds a link to it.

Bill

**Comment by lorensen** [comment]
Looks like I need to debug bit more. The layout is not correct.

**Comment by chakravarthi589** [comment]
@Bill: I totally understand about providing the link but my concern is about the layout. Python link is out of the layout.

**Comment by lorensen** [comment]
I'm fixing that now.

Thanks for pointing it out.

**Comment by chakravarthi589** [comment]
@bill: thank you.

**Comment by lorensen** [comment]
Should be fixed now.

**Comment by chakravarthi589** [comment]
@lorensen : Its fine now. Thank you!
