### ISSUE TITLE
incomplete descriptions

### ISSUE THREAD

**Issue by domibel** [lorensen/VTKExamples#32]
Some examples don't come with a good description, see e.g.
https://lorensen.github.io/VTKExamples/site/Cxx/Qt/RenderWindowUISingleInheritance/
https://lorensen.github.io/VTKExamples/site/Cxx/Qt/RenderWindowUIMultipleInheritance/

**Comment by lorensen** [comment]
Definitely bad..I'll take a look.

Thanks

**Comment by lorensen** [comment]
Fixed. Thanks!
