### ISSUE TITLE
Missing Source code in webpage

### ISSUE THREAD

**Issue by chakravarthi589** [lorensen/VTKExamples#360]

**Comment by chakravarthi589** [comment]
@lorensen ,

Source Code is missing in the below link.
https://lorensen.github.io/VTKExamples/site/Java/Interaction/ExtrudeTest/

**Comment by ajpmaclean** [comment]
Can you please commit the source code as a new commit. What was source was
a markdown file.

Andrew Maclean

**Comment by chakravarthi589** [comment]
@ajpmaclean : I thought it was missing. 
I'll try to come up with a source code. 
Thank you.
