### ISSUE TITLE
Updating to support the new module system

### ISSUE THREAD

**Issue by mathstuf** [lorensen/VTKExamples#386]
I'm working on a branch to support the new module system (https://gitlab.kitware.com/vtk/vtk/merge_requests/5020). It appears as though each individual directory supports being the top-level project. Is it actually used that way? Should I preserve that? If so, what of the `VTK_RENDERING_BACKEND` and related checks the top-level does. Should that stuff just be done in the relevant subdirectories instead?

**Comment by mathstuf** [comment]
For doing standalone support and it not appearing to be used/supported, one example is `src/Cxx/CompositeData/CMakeLists.txt`. It does `BUILD_TESTING` checks without including `CTest`. It also expects `WikiExamples_SOURCE_DIR` to be set in that block.

**Comment by lorensen** [comment]
I'll get back to you later on this.

**Comment by mathstuf** [comment]
OK, I'll first do a branch to remove logic which appears related to that support then followup with the new module system. Thanks.

**Comment by mathstuf** [comment]
`master` now supports 8.90. Closing.
