### ISSUE TITLE
Fix vtkNew syntax in Instructions/Guidelines 

### ISSUE THREAD

**Issue by jhlegarreta** [lorensen/VTKExamples#48]
At
`The use of SmartPointers is preferred in VTK examples.` ,
in the [Instructions/Guidelines](https://lorensen.github.io/VTKExamples/site/Instructions/Guidelines/) page, the syntax of the example
`vtkNew(vtkCutter> cutter;`
should be corrected to be
`vtkNew<vtkCutter> cutter;`

**Comment by lorensen** [comment]
Fixed.

Thanks!
