### ISSUE TITLE
Missing vtkHausdorffDistancePointSetFilter in VTK

### ISSUE THREAD

**Issue by patrikbi** [lorensen/VTKExamples#637]
Hi,

I'm trying to align two polydata sets using the following example:
https://lorensen.github.io/VTKExamples/site/Python/PolyData/AlignTwoPolyDatas/

But VTK is unable to import the vtkHausdorffDistancePointSetFilter. I google the issue and searched the local files and it seems like this feature isen't implemented in the current release?

I'm looking for guidance on how I can get this to work. Is there a build that can be downloaded or is there a manual way to add this filter?

Best regards,
Patrik

**Comment by ajpmaclean** [comment]
You are correct. This class is only available in the VTK master and will be
available in future releases.

Andrew Maclean
