### ISSUE TITLE
Unused #if

### ISSUE THREAD

**Issue by ScrappyCocco** [lorensen/VTKExamples#661]
In this code the #if execute the same code in the two branches

https://github.com/lorensen/VTKExamples/blob/dc8aac47c4384f9a2de9facbdd1ab3249f62ec99/src/Cxx/Qt/ShareCameraQt.cxx#L33-L39

**Comment by ajpmaclean** [comment]
Actually this is correct `setRenderWindow()`changed to `SetRenderWindow()` in versions of VTK after VTK8.90.
Please note this site is no longer being maintained, the new site is [vtk-examples](https://kitware.github.io/vtk-examples/site/).
