### ISSUE TITLE
Issues running the ReadOBJ sample

### ISSUE THREAD

**Issue by orgicus** [lorensen/VTKExamples#668]
Hi,

I'm new to VTK and amazed by the abundance of algorithms, examples and detailed tutorials.
Outstanding work from the whole team!

I have tried to the [ReadOBJ example](https://github.com/lorensen/VTKExamples/blob/master/src/Cxx/IO/ReadOBJ.cxx), however I see a warning then the program exits:
```
2021-03-29 19:00:21.828 (   0.058s) [                ]vtkInteractorStyleSwitc:37    WARN| vtkInteractorStyleSwitchBase (000002080DD8E1C0): Warning: Link to vtkInteractionStyle for default style selection.
```

This is using VTK-9.0.1 build from source using Visual Studio 2019 on Windows 10.

I've tried several obj modules, including the VTK trumpet.obj mesh, saved in the same folder as ReadOBJ.exe to avoid any confusion around paths.

I'm hoping I'm missing something simple here. 
Any hints/tips on how I may use this sample and view the loaded OBJ file ?

Many thanks,
George

**Comment by ajpmaclean** [comment]
This site is no longer being maintained. Please use the new site here [vtk-examples](https://kitware.github.io/vtk-examples/site/). This link on the new site [ReadOBJ](https://kitware.github.io/vtk-examples/site/Cxx/IO/ReadOBJ/) will also provide you with the updated code and a suitable CMakeLists.txt file. To address your comment, you are missing vtkInteractionStyle in your `find_package(VTK COMPONENTS` entry.
